[package]
name = "fp-rent"
version = "2.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Primitives for EVM rent"
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/frontier/"

[dependencies]
sp-core = { workspace = true }

[features]
default = ["std"]
std = [
  "sp-core/std"
]
